name: Java CI with Maven (Spring Boot + MySQL + Selenium)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: todoappdb
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: latest


     # - name: Install ChromeDriver
       # run: |
          #sudo apt-get update
          #sudo apt-get install -y unzip curl
      
          # Detect Chrome version
          #CHROME_VERSION=$(google-chrome-stable --version | grep -oP '\d+\.\d+\.\d+' | cut -d'.' -f1)
          #echo "Chrome version detected: $CHROME_VERSION"
      
          # Get matching ChromeDriver version
          #DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
         # echo "ChromeDriver version to download: $DRIVER_VERSION"
      
          # Download and install
         # curl -s -L -o chromedriver_linux64.zip "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
          #unzip chromedriver_linux64.zip
         # sudo mv chromedriver /usr/local/bin/
         # chmod +x /usr/local/bin/chromedriver
         # chromedriver --version


      #- name: Wait for MySQL to start
       # run: sleep 25

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h 127.0.0.1 -uroot -proot; do
            echo "Waiting for MySQL..."
            sleep 5
          done


      - name: Build with Maven
        run: mvn -B clean verify -Dspring.profiles.active=ci --file pom.xml

